import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const prod = process.argv[2] === "production";

const context = {
  banner: { js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */" },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", ...builtinModules, ...builtinModules.map((m) => `node:${m}`)],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
};

if (prod) {
  await esbuild.build({ ...context, minify: true });
  process.exit(0);
}

const builder = await esbuild.context(context);
await builder.watch();
console.log("Watching for changes...");
